import '@/app/globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/sidebar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Authjs 5: Middleware',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {


  return (
    <html lang="es">
      <body className={`bg-slate-100 ${inter.className}`} >
        <Sidebar />
        <main className="md:px-10">
          {children}
        </main>
      </body>
    </html>
  )
}